### ISSUE TITLE
selected-route-changed event gives wrong payload

### ISSUE THREAD

**Issue by sharad-purohit** [predixdesignsystem/px-app-nav#95] opened 2018-05-24 21:06 UTC
Hi,

i am having an issure where the the event mentioned above is giving false payload under `event.detail.value`

## Expected behavior and actual behavior:

- When you select a sub nav while navigating, and then select a different parent nav on the app-nav
the `selected-route-changed` event gives wrong output.

- Sub menu selection output : `['parent1', 'child1']`

- different parent menu selection output: 

  - **Actual:** `['parent1', 'parent2']` 

   -  **Expected:**`['parent2']`

 

## Steps to reproduce the problem:

- Have a `px-app-nav` with two kind of menu items,  1<sup>st</sup> with  and 2<sup>nd</sup> item with submenu

- Click on 1<sup>st</sup> menu item, event should give output as `['menu1']`
- Click on 2<sup>nd</sup> and click on submenu item event should give output as `['menu2', 'submenu1']`
- Click on 1<sup>st</sup> menu item,  event should give output as `['menu1']` but as opposed to this it is giving output as `['menu2', 'menu1']`
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

- **Version:** `2.1.7`

**Comment by alfaeddie** [comment] 2019-01-07 19:57
@sharad-purohit I can't seem to reproduce the issue you have described, neither at https://www.predix-ui.com/#/elements/px-app-nav nor on a local deployment. 

Is it possible you are mutating selected route in some observer or the event listener? Could you give some more detail of your configuration? 

I am going to close this issue for the time being, as I cannot reproduce.

**Closed by alfaeddie** 2019-01-07 19:57 UTC
